const SET_USER_AUTHENTICATION = 'SET_USER_AUTHENTICATION';
const SET_SYSTEM_CMD = 'SET_SYSTEM_CMD';
const SET_SYSTEM_CMD_DEFAULT = 'SET_SYSTEM_CMD_DEFAULT';
const SET_NEON_INTERFACE = 'SET_NEON_INTERFACE';

export { SET_USER_AUTHENTICATION, SET_SYSTEM_CMD, SET_SYSTEM_CMD_DEFAULT, SET_NEON_INTERFACE };
